### ISSUE TITLE
add from_css_string support

### ISSUE THREAD

**Issue by bilelmoussaoui** [emgyrz/colorsys.rs#2]
Currently, the library doesn't allow parsing any colors other in hex format. It would be nice if it could parse `rgb(r, g,b)` or `rgba(r, g, b, a)`

**Comment by bilelmoussaoui** [comment]
Oh it seems that it's already there https://github.com/emgyrz/colorsys.rs/blob/master/src/rgb/from_str.rs#L6
Will keep this open as the examples/documentation doesn't mention that.

**Comment by emgyrz** [comment]
README updated now.
Thanks for give rise to action
