### ISSUE TITLE
tests fail with --no-default-features

### ISSUE THREAD

**Issue by plugwash** [emgyrz/colorsys.rs#5]
While updating the colorsys crate in Debian I discovered that the tests fail when --no-default-features is used.

First there were a couple of compile errors, which were easily fixed, but then I ran into a number of tests that failed, all of them produced slightly different results with --no-default-features. 

Digging, I found the culprit was the no-std round implementation, the no-std round implementation in this crate truncates rather than rounding. I adjusted it to actually perform rounding.

I then found several other tests failing, they were failing because they had different "expected results" in std and no-std builds. I changed them to only use the "std" expected results and they passed fine.

The patch I uploaded to Debian can be found at https://salsa.debian.org/rust-team/debcargo-conf/-/blob/master/src/colorsys/debian/patches/fix-tests-no-default-features.patch

**Comment by emgyrz** [comment]
@plugwash , thanks for finding this! Fixed in 0.6.6
